### PR TITLE
migrate typography to material-ui v3.2.0

### LINKED ISSUE #678: Upgrade to @material-ui-core 3.2.0
Upgrade dependency @material-ui-core to 3.2.0 and change typography variants to new ones according to the migration guide [here](https://material-ui.com/style/typography/#migration-to-typography-v2)

### PR DESCRIPTION
**Pull request by vanyakosmos**
This PR closes #678

### CODE REVIEW

**Comment by vanyakosmos** [comment]
Looks like it was already fixed in #686.
Closing.

**Comment by vanyakosmos** [comment]
Okay, in 686 typography was fixed only in `docs`, but not in `lib`, reopening.
But I don't know how to fix errors from travis tho.

**Comment by dmtrKovalenko** [comment]
@vanyakosmos after update to new material ui version you got some typescript errors. If you cannot fix them I will

**Comment by dmtrKovalenko** [comment]
And that`s seems to be really strange but why codecov says that coverage decreases? 
You actually didn't change anything that can decrease coverage

**Comment by rosskevin** [comment]
Fixed in #695

**Pull request merged**
