### PR TITLE
Keyboard support

### PR DESCRIPTION
**Pull request by LastDreamer**
- [x] I have added 'keyboard' option to picker
- [x] I have added react-text-mask module and support for 'mask' prop

After review:
- [x] i have removed constructors
- [x] i have added TypeScript defenitions (as i can - i'm not familiar with ts at all)

### CODE REVIEW

**Comment by LastDreamer** [comment]
Done

**Comment by dmtrKovalenko** [comment]
Hi, I will test your pull request and merge it on the week end. Thank you for your job 👍

**Comment by dmtrKovalenko** [comment]
Also @alitaheri 
Would it break the persian pickers?

**Comment by alitaheri** [comment]
Don't worry about the persian pickers at all. If they ever break I'll fix them myself. Don't let them hinder progress 😎

**Comment by LastDreamer** [comment]
Best thanks for me will be the release of a new beta ;-)

**Pull request merged**
