### PR TITLE
Update material-ui to RC

### PR DESCRIPTION
**Pull request by retyui**
- [x] I have changed my target branch to **develop** :facepunch: 

## Description
Updated material-ui version to latest RC

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Please change base branch to develop. 
And thanks for this help :) 
👍

**Comment by retyui** [comment]
@dmtrKovalenko done

**Comment by retyui** [comment]
@dmtrKovalenko When do you publish to npm new version?

**Comment by dmtrKovalenko** [comment]
Today @retyui

**Comment by retyui** [comment]
@dmtrKovalenko  Thank a lot!

**Comment by NKozlov** [comment]
We are waiting for! =)

**Pull request merged**
