### PR TITLE
Add clear button

### LINKED ISSUE #29: Option to clear value or at least callback on Cancel
Hello,

first of all, thanks for these cool pickers!

I'm working on a personal project listing some data with @devexpress/dx-react-grid
and trying to use the date picker as a filter and edit widget for a date column
screenshot-budget reszli-3000-2017-11-02-15-29-56-701

when I use it for the filter, I would like to be able to clear the value selected previously
for that I would think it would be best to have a Clear button next to Cancel and OK conditioned by a prop, plus having a callback called onClear, similar to onChange, would do the trick

I'd like to have your opinion on this, as I'm new to react

thanks,
Reszli

### PR DESCRIPTION
**Pull request by cherniavskii**
- [x] I have changed my target branch to **develop** :facepunch:

Closes #29 
Closes #31 

## Description
This PR adds clear button:
peek 2017-12-27 12-01

# Breaking change:
`labelFunc` should handle `null` date value, which means that picker was cleared:
```diff
-labelFunc={(date) => {
-    return date && date.isValid() ? date.format() : 'Invalid date'; // invalidLabel
-}}

+labelFunc={(date) => {
+    if (date === null) {
+        return ''; // emptyLabel 
+    }
+    return date && date.isValid() ? date.format() : 'Invalid date'; // invalidLabel
+}}
```

# New props:
- `emptyLabel` - displayed string if date is `null` (e.g. after clear).
- `clearLabel` - label for the clear button
- `clearable` - if `false`, clear button is not displayed

# Misc:
- added `lint-fix` script to `package.json`

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Thank you for your awesome intention! Just only one mention, by the all guidelines of material design all action buttons should be right aligned (to let user easily press any action using right thumb), so I think would be better to place clear button right-aligned. 
Also native android picker with clear option have a button aligned to right as well)

**Comment by dmtrKovalenko** [comment]
Also maybe we should provide the way to customize empty label?

**Comment by cherniavskii** [comment]
Actually, according to [Material Design Guidelines](https://material.io/guidelines/components/dialogs.html#dialogs-specs):
> Dialogs should not include more than two actions

But on my Android phone native `<input type="date" />` looks like this:
screenshot_20171227-143101 1

So I think there is no "right" approach, defined my Material Design :)

I'll update clear button to make it aligned to right, not a problem ;)

-----

 > Also maybe we should provide the way to customize empty label?
There already is `emptyLabel` prop

**Comment by cherniavskii** [comment]
@alitaheri looks like we need `clearLabel` translation for Persian pickers examples

**Comment by alitaheri** [comment]
I'll do an iteration on the persian picker and fix a couple of bugs later. Thanks for the heads up 👍👍👍

**Comment by dmtrKovalenko** [comment]
@cherniavskii  Just an a lifehack ) Are you using vs-code? Just saw that you added `lint-fix` command, and if you are not using eslint plugin with autofix option in vs-code (its also available for webstorm etc) you are loosing a lot)

**Comment by cherniavskii** [comment]
@dmtrKovalenko I don't see autofix option in WebStorm built-in eslint support. I'll look for a separate plugin, thanks ;)

**Comment by dmtrKovalenko** [comment]
@cherniavskii  I have changed default `cleareable` to false, because from where I stand its just an a 'enhancement' option and for users, that already using pickers would be more convenient to add an additional configuration where they need a clear button.

**Comment by cherniavskii** [comment]
@dmtrKovalenko I thought about that too :+1:

**Comment by dmtrKovalenko** [comment]
@cherniavskii  Also, I apologize - left-aligned clear button - its better solution. I have already reverted your last commit, that reverting aligning functionality)

**Comment by cherniavskii** [comment]
no worries ;)

**Pull request merged**
