### PR TITLE
This closes #676, typescript error resolved

### LINKED ISSUE #676: DateTextField definition causes typescript compilation to fail
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |        rc17 (also tested with rc14 -> same result) |
| material-ui         |        3.2.0 |
| typescript | 3.1.1 |
| React               |         |
| Browser             |         |
| Peer library        |         | 

## Steps to reproduce
1. Install 3.2.0 of material-ui/core package.
2. Install material-ui-pickers.
3. Build with typescript (npm start / npm run build)

## Expected behavior

Build is successful, like with previous versions of material-ui/core

## Actual behavior

```
Failed to compile.

/***/node_modules/material-ui-pickers/_shared/DateTextField.d.ts
(7,45): An interface may only extend a class or another interface.
```

For me it seems to be an issue with extending the ``Omit`` type. But this is not allowed in TypeScript and therefore fails to compile. Moreover I wondered why this ``Omit`` is used at all, because in the comment it is declared as an ``@internal`` type definition. I think it should not be used in an external library then.

### PR DESCRIPTION
**Pull request by mbrn**
This PR closes #

### CODE REVIEW

**Comment by itskibo** [comment]
Doesn't close #676, as it is missing a few (similar) required changes in these files:

- DatePicker/
  - DatePickerInline.d.ts
  - DatePickerModal.d.ts

- DateTimePicker/
  - DateTimePickerInline.d.ts
  - DateTimePickerModal.d.ts

- TimePicker/
  - TimePickerInline.d.ts
  - TimePickerModal.d.ts

- wrappers/
  - InlineWrapper.d.ts
  - DatePickerInline.d.ts

**Comment by mbrn** [comment]
@itskibo look at again. I converted all typescript interfaces that you mentioned to type.

**Comment by dmtrKovalenko** [comment]
I will include your changes in #674

**Comment by itskibo** [comment]
I believe this PR can be closed, as #674 has been merged.

**Pull request closed without merging**
