### PR TITLE
Remove propTypes in production

### PR DESCRIPTION
**Pull request by TrySound**
This saves 8kb in production bundle.

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
But! We build the project in production mode. Somebody imports it through npm. And there propTypes is missing.

**Comment by TrySound** [comment]
Why anybody need to access propTypes directly? They should be used only by react internally.

**Comment by TrySound** [comment]
propTypes will validate in development mode

**Comment by dmtrKovalenko** [comment]
Does this package removes actually node module of prop-types. 
Or it removes actually Component.propTypes={} definitions?

**Comment by TrySound** [comment]
Not removes, wraps with NODE_ENV condition which is removed in production mode.

**Comment by TrySound** [comment]
Take a look here
https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types#mode

**Comment by TrySound** [comment]
The point is that prop types doesn't make sense in production code. It's a tool for developer validation.

**Comment by TrySound** [comment]
So what is your thought?

**Pull request merged**
