### PR TITLE
Allow for changes in TextField to toggle Picker

### PR DESCRIPTION
**Pull request by GaryPWhite**
Feedback from users of a tool I'm developing with material-ui-pickers is they wish they could trigger the date picker without having to click on it. Perhaps onFocus/onChange trigger could be better? I'm willing to discuss this in an issue. I didn't want to open an issue without a solution :)

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Hi, thank you for taking your time!
Yep I think it would be helpful for somehow to have an ability to open picker with tab, so I`ll merge your PR, just wanna ask you to update your target branch to develop

**Comment by GaryPWhite** [comment]
sorry about the delay. Changed the case branch!

**Comment by GaryPWhite** [comment]
Sidenote: If you'd like, I wouldn't mind putting in another PR (on develop :)) to add [react-keydown](https://www.npmjs.com/package/react-keydown) and record when the tab key is pressed to trigger the datepicker. Unless you meant when they tab INTO the datepicker, in which case, I think onFocus is the most relevant solution.

**Comment by dmtrKovalenko** [comment]
Thank you, I think we shouldnt bind an keydown event to the datepicker, and the open on focus would be sufficient

**Pull request merged**
