### PR TITLE
Fix missed mask with null value

### PR DESCRIPTION
**Pull request by LastDreamer**

### CODE REVIEW

**Comment by cherniavskii** [comment]
@LastDreamer What issue does it solve?
IIRC, passing `null` will break masked input, when picker is cleared

**Comment by dmtrKovalenko** [comment]
@LastDreamer as far I understand it fixes not displaying mask in keyboard mode, when passed null, but if the value would be null after processing by moment?

**Comment by LastDreamer** [comment]
@cherniavskii when i show picker with keyboard and mask options, but without default value (value equal null, because i need to picker be empty) - mask will no applied to picker, and i may input anything.

PR solves this issue.

**Comment by cherniavskii** [comment]
@LastDreamer Okay, I see.
But what about non-keyboard mode?
With proposed changes, `null` will be passed in case of `keyboard === false`.

P.S. In the future, please open an issue with bug description and reproducible example along with PR, which fixes this issue - this way it's clear what issue PR aims to solve and we'll have bug reports history ;)

**Comment by LastDreamer** [comment]
In non-keyboard mode mask will not be applied, because we don't need this.
Input mask - keyboard only feature

**Comment by cherniavskii** [comment]
@LastDreamer Well, right now mask works just fine in non-keyboard mode, and I don't see any reason to drop this support.

**Comment by LastDreamer** [comment]
@cherniavskii may you describe the case in which you need a mask in non-keyboard mode?

**Comment by cherniavskii** [comment]
Personally, I don't use mask at all.
But it's possible to use mask for formatting right now. Removing this support is breaking change and potentially may break something for other people.
Also, there's no any info about using keyboard/mask together in docs.

After some experiments, it looks like using mask in non-keyboard mode doesn't really make a lot of sense. I'm curious to hear what @dmtrKovalenko thinks about that.

That being said. if we decide to drop this support - we should document it and mention in breaking changes.

**Comment by cherniavskii** [comment]
Here's an example: https://codesandbox.io/s/y3pw19wjrj

**Comment by dmtrKovalenko** [comment]
As far I know in fact mask is not affect anything on rendering and displaying empty fields, so even somebody using mask with an optional keyboard toggle (switch that changes keyboard mode) would not be a breaking change, because when the keyboard is on mask would be applied, its just may cause unnecessary rerender of react text mask. Am I right?

**Comment by cherniavskii** [comment]
> because when the keyboard is on mask would be applied

yes, but if keyboard is *off*, mask wouldn't be applied

Do you think `mask` property has any sense in case of `keyboard === false`?

**Comment by dmtrKovalenko** [comment]
From where I stand in this case mask displaying just make sense to show date format and only.

**Comment by cherniavskii** [comment]
@LastDreamer let's mention in docs that `mask` only works together with `keyboard` prop - and we'll be able to merge this.

**Comment by LastDreamer** [comment]
done

**Pull request merged**
