### PR TITLE
Add `KeyboardButtonProps` for spreading props onto Keyboard IconButton

### PR DESCRIPTION
**Pull request by digitalkaoz**
## Description

for better accessibility we derive an `aria-label` from the given (optional) `label` prop for the Adornment.

i thought about adding another prop to `InputAdornmentProps`. Not sure what might be the best option here. This is just a sensible default.

What is your opinion on this?

### CODE REVIEW

**Comment by digitalkaoz** [comment]
Yeah, i thought about that too. So you suggest an additional prop?

Dmitriy Kovalenko <notifications@github.com> schrieb am Mi., 9. Jan. 2019,
19:56:

**Comment by dmtrKovalenko** [comment]
@digitalkaoz here I see 2 possibilities. Add prop something like `keyboardButtonProps` which will be spread to the IconButton. Or create something like `keyboardBtnAreaLabel={(label:  string) => string}`

**Comment by digitalkaoz** [comment]
i would go with `keyboardButtonProps`. sounds the most flexible, i'll update the PR

**Comment by dmtrKovalenko** [comment]
👍 lgtm

**Comment by dmtrKovalenko** [comment]
Find the IconButton by `WithStyles(IconButton)`

**Comment by digitalkaoz** [comment]
@dmtrKovalenko im struggeling with the test right now. what do you mean by `Find the IconButton by WithStyles(IconButton)`

**Comment by digitalkaoz** [comment]
@dmtrKovalenko im afraid im too stupid. when i fetch the html output with `html()` all is fine...maybe you can help here?

**Comment by dmtrKovalenko** [comment]
Check the html with `console.log(component.debug())`

**Comment by digitalkaoz** [comment]
as i said, the "aria-label" is rendered! maybe you can take over, and give it the final polish?

**Comment by dmtrKovalenko** [comment]
Ok I will do

**Comment by digitalkaoz** [comment]
@dmtrKovalenko any news on that one?

**Comment by dmtrKovalenko** [comment]
@digitalkaoz will be included in the next release. I am pretty busy right now so will continue asap

**Comment by digitalkaoz** [comment]
no worries, didnt wanted to stress you! :)

**Pull request merged**
