### PR TITLE
Control when you want to focus initial date in Calendar

### LINKED ISSUE #450: Allow for option to pass "initialFocusedDate" to DatePicker
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0-rc.9   |
| material-ui         |      1.2.0    |
| React               |    16.3.2     |
| Browser             |    Chrome - 66.0.3359.181     |
| Platform            |    OSX     |

## Steps to reproduce
1. Set value as null on DatePicker
2. Set minDate to a value greater than today
3. When you open the calendar, the focused date is today

## Expected behavior
I would like the ability to provide an "initial focused date" that would be highlighted when I open the picker and I don't have a selected value.  If a value is provided, this prop is ignored.

## Actual behavior
No ability to specify an initial focused date

## Live example

https://codesandbox.io/s/q7jxvqqqq9 - this code example uses an older version, which is where we first noticed the need for this prop (before we upgraded to rc9).  This feature is somewhat blocked by https://github.com/dmtrKovalenko/material-ui-pickers/issues/445

### PR DESCRIPTION
**Pull request by millnitzluan**
- [x] I have changed my target branch to **develop** :facepunch: 

## Screenshot

With `shouldFocusDateInitially` false:
with_false

With `shouldFocusDateInitially` true or without `shouldFocusDateInitially`:
without_prop

## Description
Created prop to control when you want to focus initial date, the default value of `shouldFocusDateInitially` is true, so when you want to disable it, you only need to set to false.

### CODE REVIEW

**Comment by mcMickJuice** [comment]
This does not address #450. The idea of that issue is to be able to set a default "start date" whether that's in the past or future. Current behavior is if no value is provided, today's date is highlighted.

**Comment by millnitzluan** [comment]
Yes @mcMickJuice. The initial idea is to open or not the datepicker with date highlight, start date is selected by date for example, if you send value as new Date (null) the starting date will be 1969 Wed, Dec 31

**Comment by mcMickJuice** [comment]
@millnitzluan This is what I was thinking - https://github.com/dmtrKovalenko/material-ui-pickers/pull/466

**Comment by millnitzluan** [comment]
Ah sorry, when you said focused I was thinking in the button highlighted as second screenshot.

**Pull request closed without merging**
