### PR TITLE
Fix mask behavior

### PR DESCRIPTION
**Pull request by LastDreamer**

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Please describe actually what have you changed step-by-step. 
I think its not the best way to fix this issue

**Comment by LastDreamer** [comment]
I changed check that we have valid date in text input to check that we have string that corresponds formatted date in given format.
This changes prevented premature onChange.
Now we have problem not with moment only - but with date-fns also. [Just try type 10/10/2001](https://codesandbox.io/s/535jw62ol4)

**Comment by LastDreamer** [comment]
@dmtrKovalenko `everything will be fixed simply by passing 3 argument true to the moment parse function` - and what about date-fns?

**Comment by LastDreamer** [comment]
Also now in my PR resolved [this bug - fill datepicker and then click clear](https://codesandbox.io/s/535jw62ol4)

**Comment by dmtrKovalenko** [comment]
@LastDreamer I`m sorry but I`m closing this PR due to invalid fix. [Here](https://github.com/dmtrKovalenko/material-ui-pickers/pull/295/commits/6abce340b73a1555075803f340def62d74a79b8a) is my fix and also everything works file with date-fns and 10/10/2018.  

Please can you create separate PR related to clearing keyboard input?

**Pull request closed without merging**
