### PR TITLE
Update to date-fns 2.0.0-alpha.16 and adapt format strings

### PR DESCRIPTION
**Pull request by Philipp91**
- [x] I have changed my target branch to **develop** :facepunch: 

## Description
`date-fns` changed its date formats to match the Unicode Technical Standard (see also https://github.com/date-fns/date-fns/issues/810). Now that #534 is fixed, we can update to the latest version and adjust the format strings globally without affecting compatibility with other date libraries.

Not sure if you want all the changes in `package-lock.json`, that's just what happens when I run `npm install` on my dubiously configured machine.

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Yes I think we should update. So can you also change the docs and Readme.  Where specific date fan version mentioned?

**Comment by Philipp91** [comment]
Done. The coverage report is a false positive, I don't think I'm changing the coverage in any way.

**Comment by Philipp91** [comment]
Friendly ping

**Comment by TheRusskiy** [comment]
I am beginning to think it may be worth having this as a separate package (as well as the original `date-fns-utils`) and then just reference it from the docs. Many people still use the older `date-fns` and it's gonna break material-ui-pickers for them. With so many radical changes in `date-fns` recently I wouldn't be surprised if they changed their API again.

**Comment by Philipp91** [comment]
That's definitely a reasonable argument and ultimately your choice.

If `date-fns` were stable already, it would definitely be the way to go, because a `material-ui-pickers` update shouldn't imply a `date-fns` update that forces users to do major changes to their code, assuming that they use `date-fns` for other purposes than just `material-ui-pickers`. So there might be a good reason for them to stay at the old version.
However, since `date-fns` isn't stable yet, it's okay if they change their API and users can't really complain if they already depend on it a lot. If they want the stable version ultimately, they will have to update anyway. And most users will respect the status of `date-fns` and not build a lot on it yet, so updating to the latest alpha should be doable for them.

Still, putting the utils in a separate library each (possibly with exactly the same version numbers as the respective date library) can make sense. Would that make `material-ui-pickers` (slightly) more difficult to use, i.e. would users have to add multiple dependencies? Or is there a way this can work out of the box with a single dependency?

**Pull request merged**
