### PR TITLE
Set initial focus date

### LINKED ISSUE #450: Allow for option to pass "initialFocusedDate" to DatePicker
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0-rc.9   |
| material-ui         |      1.2.0    |
| React               |    16.3.2     |
| Browser             |    Chrome - 66.0.3359.181     |
| Platform            |    OSX     |

## Steps to reproduce
1. Set value as null on DatePicker
2. Set minDate to a value greater than today
3. When you open the calendar, the focused date is today

## Expected behavior
I would like the ability to provide an "initial focused date" that would be highlighted when I open the picker and I don't have a selected value.  If a value is provided, this prop is ignored.

## Actual behavior
No ability to specify an initial focused date

## Live example

https://codesandbox.io/s/q7jxvqqqq9 - this code example uses an older version, which is where we first noticed the need for this prop (before we upgraded to rc9).  This feature is somewhat blocked by https://github.com/dmtrKovalenko/material-ui-pickers/issues/445

### PR DESCRIPTION
**Pull request by mcMickJuice**
- [x] I have changed my target branch to **develop** :facepunch: 

## Description
`DatePicker` and `DateTimePicker` accept a prop `initialFocusedDate`:

```typescript
initialFocusedDate?: DateType
```

If this prop is provided and value is null, then on calendar open, this date will have initial focus.  `minDate`/`maxDate` rules still apply (i.e. if `initialFocusedDate` is less than `minDate`, `minDate` will be focused date; if `initialFocusedDate` is greater than `maxDate`, `maxDate` will be focused date)

### CODE REVIEW

**Comment by mcMickJuice** [comment]
Still a WIP:

* [] update readme and docs
* [] write tests for BasePicker (I kept running into issues related to https://github.com/airbnb/enzyme/issues/1509 and new React context). Might look at a different way to write tests.

**Comment by mcMickJuice** [comment]
There are conflicting linting rules between react/jsx-indent and react/jsx-closing-tag-location. Still have linting errors in this new test file and in the files where state is above getDerivedStateFromProps

**Comment by mcMickJuice** [comment]
Updated prop-types file, although there were updates generated unrelated to my changes...

**Comment by mcMickJuice** [comment]
@dmtrKovalenko any feedback on this PR?  If not, any chance it can be included in next release?

**Comment by dmtrKovalenko** [comment]
I am not reviewing failed ci builds

**Comment by mcMickJuice** [comment]
@dmtrKovalenko test fixed but the build is failing due to:

> node: could not initialize ICU (check NODE_ICU_DATA or --icu-data-dir parameters)

Any insight into why this is failing?

**Comment by cherniavskii** [comment]
@mcMickJuice 
I've restarted Travis build.
It's still failing, but the reason now is https://github.com/dmtrKovalenko/material-ui-pickers/pull/500#discussion_r199710226

Let's wait for @dmtrKovalenko

**Comment by cherniavskii** [comment]
Ok, build is passing now

**Comment by mcMickJuice** [comment]
@dmtrKovalenko added.  Were there any other files that needed these typings declared?

**Pull request merged**
