### PR TITLE
Export inline pickers from entry point

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
I didnt expect to export InlinePickers from entry point in prospective of bundle increase for users that importing cjs from index.js.

**Comment by TrySound** [comment]
image

**Comment by TrySound** [comment]
You are already export it deeper. Users will rely on treeshakability in this case.

**Comment by TrySound** [comment]
However it doesn't work well yet. Mostly because of material-ui and defaultProps. The latest will be fixed soon.
image

**Comment by TrySound** [comment]
And still it doesn't matter. Every feature should be exported. The size will be increased with different ways.

**Pull request merged**
