### PR TITLE
Remove esm build

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
#661 Issue was opened because in esm module for some reason react context didnt work. I have removed that build to fix the issue but now needs to figure out what the problem. 
@TrySound have you any thoughts?

### CODE REVIEW

**Comment by TrySound** [comment]
The problem could be because of using a few instances of context. So since we use bundles as entry points users should use only one way to import things.

```
import { DatePicker } from 'material-ui-pickers';
```
vs
```
import DatePicker from 'material-ui-pickers/DatePicker';
```

This can be also solved with removing path imports. But if you want to keep it try to add helpful message in context consumer which will just assert context value.

Removing esm is a bad solution. My bundle with esm is decreased with 12kB (not just 3kB)

**Comment by TrySound** [comment]
@dmtrKovalenko So can you publish esm back?

**Comment by rosskevin** [comment]
@dmtrKovalenko @TrySound I am seeing this with my local build of #695.  I have a theory:
- cjs is deployed in the package alongside the d.ts files (appears necessary for resolution of ts).  There is no other reason that cjs is exploded other than this.
- My downstream usage is a direct import `import MuiPickersUtilsProvider from '@alienfast/material-ui-pickers/utils/MuiPickersUtilsProvider'` as opposed to index
- I think the webpack/source files are resolving based on the esm.  e.g. I have errors thrown from the esm file in the stack.

@TrySound can you take a look at the rollup config that @dmtrKovalenko put together in #695, I think esm should be rolling up es2015, but I think it currently is rolling up cjs?  Also thoughts on resolving d.ts with rollup files instead of having the exploded d.ts and cjs files together?

**Comment by TrySound** [comment]
I already said a few times. Import provider from index. It's part of the bundle.
```
import { MuiPickersUtilsProvider } from 'material-ui-pickers'
```

**Comment by rosskevin** [comment]
That's fine, but we need to prevent a direct import.  As-is, with d.ts files they resolve.  I'll try killing exploded cjs, leaving .d.ts as-is and going to index.

**Comment by rosskevin** [comment]
As long as the .d.ts files are exploded, it type checks, but will not run.  So we either need to have the .d.ts rolled up too, or stop the esm bundle and make it exploded and just rollup the cjs.

**Comment by TrySound** [comment]
How esm and d.ts are related to each other? You import from just `material-ui-pickers`. Typescript will resolve `main` and found d.ts files. Bundler will look at `module` field. Everybody take what they need.

**Comment by TrySound** [comment]
Ah, I see. We probably need to point `main` field to `lib/index.js` like formik does https://unpkg.com/formik@1.3.1/dist/

So node and typescript will take index.js and bundler will take esm bundle.

**Pull request closed without merging**
