### PR TITLE
Update date on blur

### PR DESCRIPTION
**Pull request by LastDreamer**
- [x] I have changed my target branch to **develop** :facepunch:

### CODE REVIEW

**Comment by cherniavskii** [comment]
Hi Oleg,
sorry for taking so long to take a look on your PR.

Can you add a description of changes / approach?
It will help us to review it and hopefully push it forward

**Comment by LastDreamer** [comment]
My changes do following things:

- not apply changes during keyboard input
- apply changes on press "Enter" if `props.disableOpenOnEnter` is `true`
- apply changes on blur event if fired by input (not calendar icon)
- gives new prop "parseFormats" for possibility input date with not full format. For example display format is "MM/DD/YYYY hh:mm", and parse formats is ["MM/DD/YYYY hh:mm", "MM/DD/YYYY"] - we cat type "04/29/2018" and it will be valid date

**Comment by LastDreamer** [comment]
Anything else?

**Comment by LastDreamer** [comment]
done

**Comment by LastDreamer** [comment]
done

**Comment by dmtrKovalenko** [comment]
I am sorry for so long reviewing. I was on vacation 🌴

**Pull request merged**
