### PR TITLE
fix: vertical scroll was appearing on container when weeks in month s…

### PR DESCRIPTION
**Pull request by big-kahuna-burger**
- [x] I have changed my target branch to **develop** :facepunch:

Opened in #119.
## Description
423
2017-12-21 15_54_41-checkout
424
2017-12-21 15_54_59-checkout

### CODE REVIEW

**Comment by cherniavskii** [comment]
Hi,
I'm unable to reproduce the issue.
Please provide version, material-ui version, browser and platform you are using, as well as a minimal example which reproduces this issue.
You can use [this playground](https://codesandbox.io/s/6wxqo5mxnz) to create one.

**Comment by big-kahuna-burger** [comment]
Hey, I'm unable to reproduce it today as well. I guess I'll close this one.

**Comment by big-kahuna-burger** [comment]
hah, I was running `beta.9`

**Comment by cherniavskii** [comment]
@big-kahuna-burger So it's not reproducible in beta.9? If so, we should probably revert this PR, cause it's already included in beta.10

**Pull request merged**
