### PR TITLE
Treeshake classes

### PR DESCRIPTION
**Pull request by TrySound**
`/*@__PURE__*/` is what uglify may eliminate if no usages is found. Sadly typescript does not provide correct annotation here.

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Hmm 🤔
Can you provide more info about /*@__PURE__*/

**Comment by dmtrKovalenko** [comment]
And also @TrySound. Do we need to use `sideEffects: false` in package.json?

**Comment by TrySound** [comment]
Search for `__PURE__` here https://github.com/mishoo/UglifyJS2
Yes, sideEffects will probably help with webpack.

**Comment by dmtrKovalenko** [comment]
@TrySound would you like to join as collaborator to this project? https://github.com/dmtrKovalenko/material-ui-pickers/invitations

**Comment by TrySound** [comment]
Sure

**Pull request merged**
